nnmon/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView
from django.conf import settings
from django.contrib import admin
from bt import views as bt
from bt.feeds import RssSiteNewsFeed, AtomSiteNewsFeed

from bt.api import APIResource, OperatorResource

api_resource = APIResource()
operator_api_resource = OperatorResource()

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',
        view=bt.AddForm.as_view(),
        name="homepage"),
    url(r'^list/$',
        view=bt.ViolationsList.as_view(),
        name="list_violations"),
    url(r'^list/(?P<country>\w+)/$',
        view=bt.ViolationsList.as_view(),
        name="filter_country"),
    url(r'^list/(?P<country>\w+)/(?P<operator>\w+)/$',
        view=bt.ViolationsList.as_view(),
        name="filter_operator"),
    # violation cannonical url and redirections
    url(r'^(?P<id>[0-9]*)$',
        RedirectView.as_view(url='/view/%(id)s')),
    url(r'^view/(?P<id>[0-9]*)$',
        view=bt.ViolationView.as_view(),
        name="violation_url"),
    url(r'^attach/(?P<id>[0-9]*)$',
        view=bt.get_attach,
        name="attach"),
    # different data outputs
    url(r'^csv$',
        view=bt.ascsv,
        name="csv_output"),
    url(r'^ods$',
        view=bt.asods,
        name="ods_output"),
    url(r'^rss/$',
        view=RssSiteNewsFeed(),
        name="rss_output"),
    url(r'^atom/$',
        view=AtomSiteNewsFeed(),
        name="atom_output"),
    url(r'^activate/$',
        view=bt.activate,
        name="activate"),
    url(r'^confirm/(?P<id>[0-9a-z]*)$',
        view=bt.confirm,
        name="confirm"),
    url(r'^confirm/(?P<id>[0-9]*)/(?P<name>.*)$',
        view=bt.confirm,
        name="confirm_full"),
    url(r'^moderate/$',
        view=bt.moderate,
        name="moderate"),
    url(r'^lookup/$',
        view=bt.LookupView.as_view(),
        name="lookup"),
    url(r'^accounts/logout$',
        'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/',
        include('registration.urls')),
    url(r'^comments/',
        include('django_comments.urls')),
    url(r'^about/$',
        TemplateView.as_view(template_name='nn.html')),
    url(r'^start/$',
        TemplateView.as_view(template_name='start.html')),
    url(r'^captcha/',
        include('captcha.urls')),
    url(r'^admin/',
        include(admin.site.urls)),
    url(r'^api/',
        include(api_resource.urls)),
    url(r'^api/',
        include(operator_api_resource.urls)),
    url(r'^search/',
        bt.ViolationSearchView.as_view(template_name='search/search.html')),
)

if settings.DEV_SERVER == True:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_PATH}),
    )

bt/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_comments.moderation import CommentModerator, moderator

COUNTRIES = (
    ('BE', _('Belgium')),
    ('BG', _('Bulgaria')),
    ('CZ', _('Czech Republic')),
    ('DK', _('Denmark')),
    ('DE', _('Germany')),
    ('EE', _('Estonia')),
    ('IE', _('Ireland')),
    ('EL', _('Greece')),
    ('ES', _('Spain')),
    ('FR', _('France')),
    ('IS', _('Iceland')),
    ('IT', _('Italy')),
    ('CY', _('Cyprus')),
    ('LV', _('Latvia')),
    ('LT', _('Lithuania')),
    ('LU', _('Luxembourg')),
    ('HU', _('Hungary')),
    ('MT', _('Malta')),
    ('NL', _('Netherlands')),
    ('NO', _('Norway')),
    ('AT', _('Austria')),
    ('PL', _('Poland')),
    ('PT', _('Portugal')),
    ('RO', _('Romania')),
    ('SI', _('Slovenia')),
    ('SK', _('Slovakia')),
    ('FI', _('Finland')),
    ('SE', _('Sweden')),
    ('UK', _('United Kingdom')),
    )

RESOURCES = (
    ('port', _('port')),
    ('protocol', _('protocol')),
    ('service', _('service')),
    ('site', _('site')),
    ('user', _('user')),
    ('ip', _('ip')),
    )
TYPES = (
    ('blocking', _('Blocking')),
    ('throttling', _('Throttling')),
    )
MEDIA = (
    ('fixed', _('Fixed')),
    ('mobile', _('Mobile')),
    )
STATUS = (
    ('moreinfo', _('Need more info')),
    ('new', _('New')),
    ('verified', _('Verified')),
    ('duplicate', _('Duplicate')),
    ('ooscope', _('Out of scope')),
    ('closed', _('Closed')),
    )

class Operator(models.Model):
    """
    Define the concept of an internet provider/network operator
    """
    name = models.CharField(max_length=256)
    logo = models.ImageField(upload_to='operator_logo', null=True, blank=True)

    def reported_violations(self):
        return self.violations.count()
    reported_violations.short_description = 'Reported Violations'

    def __unicode__(self):
        return self.name


class Violation(models.Model):
    country = models.CharField(max_length=2, choices=COUNTRIES)
    operator_ref = models.ForeignKey(Operator, related_name="violations")
    contract = models.CharField(max_length=256, blank=True)
    resource = models.CharField(max_length=20, choices=RESOURCES, blank=True)
    resource_name = models.CharField(max_length=4096, blank=True)
    type = models.CharField(max_length=20, choices=TYPES, blank=True)
    media = models.CharField( max_length=20, choices=MEDIA, blank=True)
    temporary = models.BooleanField( )
    contractual = models.BooleanField()
    contract_excerpt = models.TextField(blank=True)
    loophole = models.BooleanField()
    activationid= models.CharField(max_length=128, blank=True)
    state = models.CharField(max_length=20, choices=STATUS, default='new', blank=True)
    editorial = models.TextField(blank=True)

    def confirmations(self):
        return self.confirmation_set.filter(key='').count()

    class Admin:
        pass

    @property
    def operator(self):
        return self.operator_ref.name

    @models.permalink
    def get_absolute_url(self):
        return ('violation_url', (), 
            {'id': self.pk })

    def __unicode__(self):
        return "#%s %s/%s" % (self.pk, self.country, self.operator)


class Comment(models.Model):
    submitter_email = models.EmailField()
    submitter_name = models.CharField(max_length=20)
    consent = models.BooleanField( )
    comment = models.TextField()
    timestamp = models.DateTimeField()
    violation = models.ForeignKey(Violation)

    class Admin:
        pass

    def __unicode__(self):
        return _("Comment #%s") % (self.pk)

class Attachment(models.Model):
    storage = models.FileField(upload_to='static')
    name= models.CharField(max_length=512)
    type= models.CharField(max_length=512)
    comment = models.ForeignKey(Comment)

    class Admin:
        pass

    def __unicode__(self):
        return self.name

class Confirmation(models.Model):
    key=models.CharField(max_length=64, blank=True)
    email=models.EmailField()
    violation = models.ForeignKey(Violation)

    class Admin:
        pass

class ViolationModerator(CommentModerator):
    email_notification = True
    moderate_after        = 0
    def moderate(self, comment, content_object, request):
        return True

if Violation not in moderator._registry:
    moderator.register(Violation, ViolationModerator)

class FeaturedCase(models.Model):
    case = models.OneToOneField(Violation)

    class Admin:
        pass

    def __unicode__(self):
        return u"*%s*" % self.case

bt/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from haystack.forms import SearchForm
from haystack.query import SearchQuerySet
from bt.models import Violation, COUNTRIES, RESOURCES, TYPES, MEDIA
from bt.multifile import MultiFileField
from operator import itemgetter
from captcha.fields import CaptchaField

class AdvancedEditor(forms.Textarea):
	class Media:
		js = (settings.MEDIA_URL+'/js/tinymce/tiny_mce.js',)

	def __init__(self, language=None, attrs=None):
		self.language = language or settings.LANGUAGE_CODE[:2]
		self.attrs = {'class': 'advancededitor'}
		if attrs: self.attrs.update(attrs)
		super(AdvancedEditor, self).__init__(attrs)

class AddViolation(forms.Form):
   resource_name = forms.CharField(required=True, max_length=4096, label=_('Please specify the affected resource'), help_text=_("What service or site, or person is unavailable or seems artificially slowed down. e.g. VoIP, p2p, filesharing, specific websites, etc."))
   country = forms.ChoiceField(required=True, choices=(('',''),)+tuple(sorted(COUNTRIES,key=itemgetter(1))), label=_("Country"), help_text=_('EU member state where the restriction is reported.'))
   operator = forms.CharField(required=True, max_length=256, label=_("Operator"), help_text=_('The ISP or operator providing the Internet service.'))
   contract = forms.CharField(required=True, max_length=256, label=_("Contract"), help_text=_('The specific contract at the ISP provider. (please be as specific as possible)'))
   media = forms.ChoiceField(required=True, choices=(('',''),)+tuple(sorted(MEDIA,key=itemgetter(1))), label=_('Is the Internet connection over mobile or fixed line?'))
   comment = forms.CharField(required=True, widget=AdvancedEditor(), label=_('Please describe the symptoms you are experiencing.'))
   email = forms.EmailField(required=True, label=_('Email (set this to enable saving)'), help_text=_("We need your email to validate your report. Your email address is obligatory, but we will never use your personal data for anything else than checking the submission. (see next for an optional exception)"))
   consent = forms.BooleanField(required=False, label=_("I want to help further"), help_text=_("We need your consent to contact you for clarifications regarding your report. This is optional, but helps us improve the quality of the reports. Thanks!"))
   nick = forms.CharField(required=False, label=_("Name or nickname"), help_text=_("We need some name to display that instead of an email address."))
   attachments = MultiFileField(required=False, label=_("Attach screenshot, document or any other relevant information."))
   resource = forms.ChoiceField(required=False, choices=(('',''),)+tuple(sorted(RESOURCES,key=itemgetter(1))), label=_('What is the affected resource type. (optional)'))
   type = forms.ChoiceField(required=False, choices=(('',''),)+tuple(sorted(TYPES,key=itemgetter(1))), label=_('Is the Resource Blocked or otherwise discrimated? (optional)'))
   temporary = forms.BooleanField(required=False, label=_('Is the restriction only temporary, e.g. due to network overload? (optional)'))
   loophole = forms.BooleanField(required=False, label=_('Is there another offer provided by this Operator which removes this restriction? (optional)'))
   contractual = forms.BooleanField(required=False, label=_('Is the restriction described in the subscribers contract? (optional)'))
   contract_excerpt = forms.CharField(required=False, widget=AdvancedEditor(), label=_('Please copy the relevant section describing the restriction from the user contract. (optional)'))
   captcha = CaptchaField(label=_("In order to protect against spam, please fill in the result of the following calculation. (note the + and the * are somewhat confusing)"))

class SearchViolation(SearchForm):
   country = forms.ChoiceField(required=True, choices=(('',''),)+tuple(sorted(COUNTRIES,key=itemgetter(1))), label=_("Country"), help_text=_('EU member state where the restriction is reported.'))
   operator = forms.CharField(required=True, max_length=256, label=_("Operator"), help_text=_('The ISP or operator providing the Internet service.'))
   contract = forms.CharField(required=True, max_length=256, label=_("Contract"), help_text=_('The specific contract at the ISP provider. (please be as specific as possible)'))
   media = forms.ChoiceField(required=True, choices=(('',''),)+tuple(sorted(MEDIA,key=itemgetter(1))), label=_('Is the Internet connection over mobile or fixed line?'))

   def search(self):
       # By default, teh search field is q. So let's check if it's empty
       if not self.cleaned_data['q']:
           sqs = SearchQuerySet().all()
       else:
           sqs = super(SearchViolation, self).search()

       if not self.is_valid():
           return self.no_query_found()

       if self.cleaned_data['operator']:
           sqs = sqs.filter(operator=self.cleaned_data['operator'])

       if self.cleaned_data['contract']:
           sqs = sqs.filter(contract=self.cleaned_data['contract'])

       if self.cleaned_data['media']:
           sqs = sqs.filter(media=self.cleaned_data['media'])

       if self.cleaned_data['country']:
           sqs = sqs.filter(country=self.cleaned_data['country'])

       return sqs

class QuickSearchViolation(forms.Form):
    query = forms.CharField(required='True', max_length=256, label=_("Search"), help_text=_('Search for an existing violation'))

nnmon/templates/feeditem.html
{% load bt %}
{% load i18n %}
{%if obj.comment_set.all.0%}
 <h3>{%trans "Description" %}</h3>
 <div class="description-node">
   <div class="description">{{obj.comment_set.all.0.comment|safe}}</div>
   <span class="submitter">Submitter: {%if obj.comment_set.all.0.submitter_name%}{{obj.comment_set.all.0.submitter_name}}{%else%}{{obj.comment_set.all.0.submitter_email}}{%endif%}</span> - <span class="comment_date">{{obj.comment_set.all.0.timestamp|date:"SHORT_DATE_FORMAT" }}</span>
   {%if obj.comment_set.all.0.attachment_set.all%}
   <div class="attachs">
      {% trans "Attachments" %}
     <ul>
       {%for a in obj.comment_set.all.0.attachment_set.all%}
       <li><a href="{{a.storage.url}}">{{a.storage.name}}</a></li>
       {%endfor%}
     </ul>
   </div>
   {%endif%}
 </div>
{%endif%}
<ul>
{%if obj.media%}<li>{% trans "Media" %}: {{obj.media}}</li>{%endif%}
{%if obj.resource_name%}<li>{% trans "Affected Resource/service" %}: {{obj.resource_name}}</li>{%endif%}
{%if obj.type%}<li>{% trans "Type" %}: {{obj.type}}</li>{%endif%}
{%if obj.temporary%}<li>{% trans "Temporary restriction" %}: {% trans "yes" %}</li>{%endif%}
{%if obj.loophole%}<li>{% trans "Loophole offering" %}: {% trans yes %}}</li>{%endif%}
{%if obj.contractual%}<li>{% trans "Contractual restriction" %}: {% trans "yes" %}</li>{%endif%}
</ul>
{%if obj.contract_excerpt%}{% trans "Contract excerpt" %}: {{obj.contract_excerpt|safe}}{%endif%}

nnmon/templates/index.html
{% extends "base.html" %}
{% load bt %}
{% load i18n %}
{% block active_tab_home %}id="current"{% endblock %}
{% block styles %}
<link rel="stylesheet" type="text/css" media="all" href="/static/css/jquery-ui.css" />
{% endblock %}

{% block scripts %}
<script type="text/javascript">
function focushandlers(ed) {
	var s = ed.settings;
	var realID = $('#'+ed.id+'_tbl');
	tinymce.dom.EventUtils.bind(ed.getWin(), 'focus', function(e) {
		if($(realID)) {
			/console.log(realID);
			realID.parents('.fieldWrapper').find('.help_text').show();
		}
	});
	tinymce.dom.EventUtils.bind(ed.getWin(), 'blur', function(e) {
		if($(realID)) {
			/console.log(realID);
			realID.parents('.fieldWrapper').find('.help_text').hide();
		}
	});
}
$(document).ready(function(){
	{% if not form.is_bound %}
	$(".fieldWrapper").hide();
	$("#id_resource_name").parent().parent().show();
	$("#id_country").parent().parent().show();
	$("#id_operator").parent().parent().show();
	$("#id_contract").parent().parent().show();
	$("#id_media").parent().parent().show();
	$("#save_button").hide();
	{% else %}
	if($("#id_contractual").attr('checked')==false) {
		$("#id_contract_excerpt").parent().parent().hide();
	}
	$("#show_optionals").show();
	$("#optional .fieldWrapper").hide();
	if ($('#id_email').val().length>0) {
		$('#id_captcha_0').parent().parent().show();
		$('#save_button').removeAttr('disabled');
		$("#show_optionals").show();
	}
	{% endif %}
</script>
{% endblock %}

{%block content%}
<div id='global'>
	{% if messages %}
	<ul class="messages">
		{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
		{% endfor %}
	</ul>
	{% endif %}
	<div id='addForm' class='index'>
		<h2>{% trans "Add New Case" %}</h2>
		<p>{% trans "Please report cases of operators restricting or throttling access to content, services or applications. For a more precise description of what to report, check our <a href='/about/#guidelines'>guidelines</a>." %}
		<form name="addForm" enctype="multipart/form-data" action="{% root_url %}/add/" method="post">
			{% for field in form %}
			{% if field.html_name = 'comment' %}<div class="hidden errorlist">{% trans "There are already some reports for this Operator/Contract, please check if yours is already among them:" %}<ul id="similar_cases"></ul></div>{%endif%}
			{% if field.html_name = 'resource' %}<div id="show_optionals">{% trans "Provide optional details" %}</div><div id="optional">{%endif%}
				<div class="fieldWrapper">
					{% if field.help_text %}<span class="help_text">{{ field.help_text }}</span>{% endif %}
					<span class="innerfield">
						{{ field.errors }}
						{{ field.label_tag }} {{ field }}
					</span>
				</div>
				{% endfor %}
			</div>
			{% csrf_token %}
			<input id="save_button" type="submit" value="{% trans "save" %}" />
		</form>
	</div>
	<div id='content'>
		<h2>{% trans "On the Internet, <strong>you</strong> decide what you do, right? <i>Not anymore!</i>" %}</h2>
		<p>{% trans "Large telecommunication providers want to control what you do online. They want to block and throttle some of your communications, and charge you to use certain online services, content and applications." %}</p>
		<p>{% trans "Now is the time to fight back!" %}</p>
		<p>{% trans "Help us chart all the ways that internet providers are violating our online freedom. Tell us about how your landline or mobile operator Internet provider restricts your connection. You can do so in less than two minutes!" %}
		<p>{% trans "We will report these violations to the European Commission and national authorities and demand action to address them." %}</p>
		<p>{% trans "Don't hesitate to give us feedback on this application by reporting any idea or issue with RespectMyNet.eu here : <a href='https://nnmon.quadpad.lqdn.fr/feedback'>Feedback pad page</a>" %}</p>
		<h2 id="stats-title">{% trans "Statistics" %}</h2>
		<div id="stats_graph" ></div>
		<ul id="stats">
			{% for t, n in stats %}
			<li class="stat"><dl><dt class="inline">{{t}}</dt><dd class="inline"><strong>{{n}}</strong></dd></dl></li>
			{% endfor %}
		</ul>

		<h2 id="featured-title">{% trans "Featured Cases" %}</h2>
		<table id="featured_cases">
			<thead>
				<tr>
					<th style="width: 70%;">{% trans "Infringing offering" %}</th>
					<th>{% trans "Confirmed" %}</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for violation in violations %}
				<tr>
					<td><a href="{{ violation.get_absolute_url }}">{{ violation.operator }} ({{ violation.country|country }}) {{ violation.contract }}</a>
						<div class="info-validate">
							<form method="get" id="{{ violation.pk }}" class="confirm_form" >
								<label>{% trans "In order to <strong>confirm</strong> this report, please enter your email address" %}</label>
								<br/><input type="text" name="email" />
								<input type="submit" value="{% trans "OK" %}" />
								<input type="button" value="{% trans "Cancel" %}" class="cancel-button" />
								<input type="hidden" value="{{ violation.pk }}" />
							</form>
						</div>
					</td>
					<td class='align-right'>{{ violation.confirmations }}</td>
					<td class='align-right'><input type="button" class="confirm button" value="{% trans "Me too!" %}" />
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<div id="description" class='round-box'>
							<strong>{% trans "Affected Resource" %}:</strong> {{violation.resource_name}}
							{%for c in violation.comment_set.all%}
							<div class="description">{{c.comment|safe}}</div>
							<span class="submitter">{%if c.submitter_name%}{{c.submitter_name}}{%else%}{{c.submitter_email}}{%endif%}</span> - <span class="comment_date">{{c.timestamp|date:"SHORT_DATE_FORMAT" }}</span>
						</div>
						{%endfor%}
	</div>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
</div>
</div>
{%endblock%}

nnmon/templates/view.html
{% extends "base.html" %}
{% load bt %}
{% load i18n %}
{% load comments %}
{% block active_tab_cases %}id="current"{% endblock %}
{% block styles %}
{% endblock %}
{% block adminext %}
, <a href="{%root_url%}/admin/bt/violation/{{v.id}}/ ">{% trans "Edit" %}</a>
{% endblock %}
{% block scripts %}
<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" charset="utf-8">
function bindPostCommentHandler() {
    $('.toggle').click(function(){
      $(this).hide();
      $(this).next().show();
    });
    $('#comment_form form input.submit-preview').remove();
    $('#comment_form form').submit(function() {
        var postdata=$('#comment_form form').serialize()+'&csrftoken={{csrf_token}}';
        $.ajax({
            type: "POST",
            data: postdata,
            url: "{% comment_form_target %}",
            cache: false,
            dataType: "html",
            success: function(html, textStatus) {
                $('#comment_form form').replaceWith(html+" "+"{% trans 'It will appear here after moderation.' %}");
                bindPostCommentHandler();
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                $('#comment_form form').replaceWith("{% trans 'Your comment was unable to be posted at this time. We apologise for the inconvenience.' %}");
            }
        });
        return false;
    });
}

$(document).ready(function() {
    bindPostCommentHandler();
  $('.confirm_form').submit(function() {
     var self=this;
     var email=$(this).children('input:first').attr('value');
     if( email.length>0) {
        $.ajax({url: '/confirm/'+$(this).attr('id')+'/'+email, success: function(data) { $(self).html(data); }});
     } else {
        console.log($(this).find('[type=submit]'));
        $(this).find('[type=text]').focus();
     }
     return false;
     });
    $('span').hover(function(){$('span#'+this.id+'_tooltip').fadeIn();}, function(){$('span#'+this.id+'_tooltip').hide();});
});
</script>
{% endblock %}

{%block content%}
<div id='global'>
  <h2>{{v.operator}} ({{v.country}}) {{v.contract}}</h2>
<div id="report">
	<div id="icons">
		<span id="verified_tooltip" class="tooltip">{% trans "This case was verified by the management team" %}</span>
		<span class="tooltip_on">{%if v.confirmations == 0 %} {% trans "Nobody has yet confirmed the case. Feel free to do it" %} {%else%} {{v.confirmations}} {%if v.confirmations == 1 %} {% trans "person has confirmed this case" %} {%else%} {% trans "persons have confirmed this case" %} {%endif%} {%endif%}</span>
		{% if v.state == 'verified' %}<span id="verified"></span> |{% endif %}
		<span id="confirmations">{{v.confirmations}}</span> |
	</div>

  <dl>{%if v.resource_name%}<dt>{% trans "Affected resource" %}</dt><dd>{{v.resource_name}}</dd>{%endif%}
  {%if v.type%}<dt>{% trans "Type" %}</dt><dd>{{v.type|type}}</dd>{%endif%}
  {%if v.media%}<dt>{% trans "Media" %}</dt><dd>{{v.media|media}}</dd>{%endif%}
  {%if v.state%}<dt>{% trans "Status" %}</dt><dd>{{v.state|status}}</dd>{%endif%}
  {%if v.temporary%}<dt>{% trans "Temporary restriction" %}</dt><dd>{% trans "yes" %}</dd>{%endif%}
  {%if v.loophole%}<dt>{% trans "Another offer provided by the same operator removes this restriction" %}</dt><dd>{% trans "yes" %}</dd>{%endif%}
  {%if v.contractual%}<dt>{% trans "Contractual restriction" %}</dt><dd>{% trans "yes" %}</dd>{%endif%}
  {%if v.contract_excerpt%}<dt>{% trans "Contract excerpt" %}</dt><dd class='text'>{{v.contract_excerpt|safe}}</dd>{%endif%}
  {%if v.comment_set.all%}</dl>
</div>

{% if v.editorial %}
<div id="editorial" class='round-box'>
   <h3>{% trans "RespectMyNet note" %}</h3>
   {{v.editorial|safe}}
</div>
{% endif %}

<div id="description" class='round-box'>
    <h3>{%trans "Description" %}</h3>
    {%for c in v.comment_set.all%}
    <div class="description-node">
	  {%if c.attachment_set.all%}
	  <div class="attachs">
         <h4>{% trans "Attachments" %}</h4>
        <ul>
          {%for a in c.attachment_set.all%}
          <li><a href="{% url attach a.id %}">{{a.name}}</a></li>
          {%endfor%}
        </ul>
      </div>
      {%endif%}
      <div class="description">{{c.comment|safe}}</div>
      <span class="submitter">{%if c.submitter_name%}{{c.submitter_name}}{%else%}{{c.submitter_email}}{%endif%}</span> - <span class="comment_date">{{c.timestamp|date:"SHORT_DATE_FORMAT" }}</span>
    </div>
    {%endfor%}
</div>


  <h3>{%trans "This restriction affects me too" %}</h3>
  <div class="info-validate" style="display: inline-block;">
    <form method="get" id="{{ v.pk }}" class="confirm_form" >
        <label>{% trans "In order to <strong>confirm</strong> this report, please enter your email address" %}</label>
        <input type="text" name="email" />
        <input type="hidden" value="{{ v.pk }}" />
        <input type="submit" value="{% trans "Me too!" %}" />
      </form>
   </div>
  {%endif%}
  {% if not key %}
  <div id="comments">
  <h3>{% trans "Comments" %}</h3>
  {% get_comment_list for v as cmt_list %}
  {% for comment in cmt_list %}
  <div class="comment">
     <p>{{ comment.user_name }} - {{ comment.submit_date }}</p>
     <p>{{ comment.comment|striptags|urlize|linebreaks }}</p>
  </div>
  {% endfor %}
  <div class="toggle button">{% trans "Add comment" %}</div>
  <div id="comment_form" style="display: none;">
    {% render_comment_form for v %}
  </div>
  {% else %}
  <br />
  <a class="button" href='/moderate/?key={{key}}&action=approve'>{% trans "Approve Submission" %}</a>
  <a class="button" href='/moderate/?key={{key}}&action=delete'>{% trans "Delete Submission" %}</a>
  </div>
  {% endif %}
</div>
{%endblock%}